inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/IndentationWidth:
  IgnoredPatterns: ['^\s*private$']

Style/BracesAroundHashParameters:
  Enabled: false

Metrics/LineLength:
  Max: 100
