AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false # Using Ruby 2.4 doesn't need it

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes