language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem install bundler
script: bundle exec rake spec
gemfile:
  - gemfiles/rails5.gemfile
notifications:
  email:
    - support@travellink.com.au
sudo: false
cache: bundler
