require 'ruby_core_extensions/recursive/array'
require 'ruby_core_extensions/recursive/big_decimal'
require 'ruby_core_extensions/recursive/date'
require 'ruby_core_extensions/recursive/date_time'
require 'ruby_core_extensions/recursive/fixnum'
require 'ruby_core_extensions/recursive/hash'
require 'ruby_core_extensions/recursive/object'
require 'ruby_core_extensions/recursive/time'
